apiVersion: v1
kind: ReplicationController
metadata:
  name: hello-limit
spec:
  replicas: 1  
  selector:    
    application: hello-limit
  template:    
    metadata:
      labels:  
        application: hello-limit 
    spec:
      containers:
      - name: hello-limit
        image: quay.io/redhattraining/hello-world-nginx:v1.0
        ports:
        - containerPort: 8080
          protocol: TCP
